In [172]:
import firebase_admin
from firebase_admin import credentials,firestore,initialize_app
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 100)
from typing import List,Dict,Tuple


In [173]:
cred = credentials.Certificate("/Users/kinsho/workspace/micce-firebase-secret-key/micce-travel-firebase-adminsdk-3fcnp-b289dc5911.json")
app = initialize_app(cred, name="micce-app")


ValueError: Firebase app named "micce-app" already exists. This means you called initialize_app() more than once with the same app name as the second argument. Make sure you provide a unique name every time you call initialize_app().

In [174]:
firestore_client  = firestore.client(app=app)
spots = firestore_client.collection("Spot").stream()


In [175]:
spot_list = list()
for spot in spots:
    spot_list.append(spot.to_dict())

df = pd.DataFrame(spot_list)

df.head(10)

type                    id  googleReviewScore  \
0  restaurant  01WKW1kqcDIry4xb3kNY                4.0   
1  restaurant  02FsRcZNGrHoXsSuJFXk                0.0   
2     tourist  02raxFhXNoRmzXXPk0Zo                4.2   
3       hotel  039zAGnA0gIyIQ0Hn5Pz                4.3   
4        shop  04HBHFCyUVFcf36g9bD6                3.9   
5  restaurant  06fGcNy4BG3qmY4bKvOU                4.3   
6       other  07Wm6ZbR6rjYYqvLeyGV                4.4   
7       other  07rX0B5QPj2DOQH6bAJY                3.6   
8     tourist  08MBgpVsG5lcbKQkFxCl                4.0   
9     tourist  0Az4z8hSgz9vm6RjaDnU                4.1   

                                                 url   longitude status  \
0                                                     134.649435    ACC   
1                                                     128.766697    ACC   
2  https://korean.visitkorea.or.kr/detail/ms_deta...  129.124401    ACC   
3                       http://gracery.com/shinjuku/  139.702054    ACC   
4                              http://churro101.com/  126.924263    ACC   
5                    http://instagram.com/kajaguruma  127.011514    ACC   
6                                                     139.765058    ACC   
7  https://www.seiburailway.jp/railway/ekimap/tam...  139.418368    ACC   
8  https://e-zofukuoka.com/?utm_source=googlemybu...  130.363753    ACC   
9                            https://www.nixe.co.jp/  141.182130    ACC   

                                    primaryImageFile     city   prefecture  \
0  spots/images/26555cc0-eec1-4621-a10f-583b96cae...      姫路市          兵庫県   
1                                               None      キメ市         None   
2  spots/images/60a692d3-5c92-4dbb-9d22-c2ed31f34...   Nam-gu        Busan   
3  spots/images/7c0c50fa-23e6-4b0e-a09c-ef0b5a56c...      新宿区          東京都   
4  spots/images/13302dde-5195-4ca6-90ee-25e85a06e...  Mapo-gu        Seoul   
5  spots/images/2eb92b43-c73e-4023-8ddd-4db64bc95...    Suwon  Gyeonggi-do   
6  spots/images/b5e48e64-aeba-41ee-8cc3-28d2c5d6c...      八丈町          東京都   
7  spots/images/c271941e-13c9-4996-96c2-4e821bad6...      立川市          東京都   
8  spots/images/0c88c920-6201-4027-b1cc-7db288142...      福岡市          福岡県   
9  spots/images/098fb3bc-e59f-4093-921a-5496eb866...      登別市          北海道   

                name movieUrl  \
0              トンデムン     None   
1              석쇠불고기     None   
2         五六島スカイウォーク     None   
3        ホテルグレイスリー新宿     None   
4         Churro 101     None   
5              카자구루마     None   
6           西山（八丈富士）     None   
7              玉川上水駅     None   
8  BOSS E･ZO FUKUOKA     None   
9        登別マリンパークニクス     None   

                                          spotImages  \
0  [{'imagePath': 'spots/images/26555cc0-eec1-462...   
1                                               None   
2  [{'originUrl': 'www.instagram.com/p/B3suxoQl5A...   
3  [{'imagePath': 'spots/images/7c0c50fa-23e6-4b0...   
4  [{'imagePath': 'spots/images/13302dde-5195-4ca...   
5  [{'imagePath': 'spots/images/2eb92b43-c73e-402...   
6  [{'originUrl': 'https://maps.google.com', 'ima...   
7  [{'imagePath': 'spots/images/c271941e-13c9-499...   
8  [{'originUrl': 'https://www.instagram.com/p/Cl...   
9  [{'imagePath': 'spots/images/098fb3bc-e59f-409...   

                         updatedAt  \
0 2023-02-16 08:10:25.728000+00:00   
1 2023-02-23 09:12:10.126000+00:00   
2 2023-03-01 17:00:08.324247+00:00   
3 2023-02-14 12:32:24.643876+00:00   
4 2023-03-01 15:15:04.544077+00:00   
5 2023-03-01 16:56:39.163951+00:00   
6 2023-02-08 11:21:24.932000+00:00   
7 2023-03-02 13:38:05.340000+00:00   
8 2023-01-20 07:10:56.717777+00:00   
9 2023-01-20 07:10:57.698914+00:00   

                                      affiliateInfos         phone  \
0  [{'URL': 'https://tabelog.com/rstLst/?vs=1&sa=...  079-230-2566   
1  [{'Category': 'tabelog', 'URL': 'https://tabel...                 
2                                               None  051-607-6395   
3  [{

In [176]:
korea_airport_df = df[(df["name"] == "仁川国際空港") | (df["name"] == "金浦国際空港")]
korea_airport_df["type"]= "airport"
korea_airport_df = korea_airport_df.fillna("")
korea_airport_df.head(10)

/var/folders/tm/7v5m6cg144g467bsj7zgsxgc0000gn/T/ipykernel_6970/2873538289.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  korea_airport_df["type"]= "airport"


type                    id  googleReviewScore  \
1743  airport  mR58qvOdnBcICh2e8xz5                4.4   
1907  airport  rDB97yQLFzdoprgE3kGe                4.6   

                                      url   longitude status  \
1743  http://www.airport.co.kr/mbs/gimpo/  126.794474    ACC   
1907               http://www.airport.kr/  126.440696    ACC   

                                       primaryImageFile     city prefecture  \
1743  spots/images/7c7fa1f0-e180-4789-b57d-c62f579b2...    Seoul              
1907  spots/images/e4440daf-bd0e-43c9-a699-f0b9a2fcf...  Jung-gu    Incheon   

        name movieUrl                                         spotImages  \
1743  金浦国際空港           [{'originUrl': 'https://maps.google.com', 'ima...   
1907  仁川国際空港           [{'originUrl': 'https://www.instagram.com/p/CD...   

                            updatedAt affiliateInfos      phone  priceLevel  \
1743 2023-01-20 07:32:29.026844+00:00                 1661-2626           0   
1907 2023-01-20 07:33:17.078423+00:00                 1577-2600           0   

                                           openingHours  hasInstagramImages  \
1743                                                                  False   
1907  {'PermanentlyClosed': None, 'WeekdayText': ['月...                True   

       latitude                        createdAt  \
1743  37.558654 2023-01-16 12:24:21.764000+00:00   
1907  37.460191 2023-01-03 08:05:32.908000+00:00   

                             instagramImageUrls                googlePlaceId  \
1743                                             ChIJF6qs-dCcfDURVMw5Ij-Qd6w   
1907  [https://www.instagram.com/p/CDkoAhinxUd]  ChIJWfpeOoOaezUR1L5cy5agS40   

                                      address                  quadKey  \
1743  112 Haneul-gil, Gangseo-gu, Seoul, 大韓民国  13211032003012102211121   
1907  272 Gonghang-ro, Jung-gu, Incheon, 大韓民国  13211023113230231303221   

     rakutenHotelMinCharge rakutenHotelNo tags rakutenHotelName  \
1743                                                              
1907                                                              

     rakutenHotelRatingInfo rakutenHotelSpecial  
1743                                             
1907

In [177]:
df = df.fillna("")
exist_tag__df = df[df["tags"] != ""]
exist_tag__df.head(2)

type                    id  googleReviewScore  \
4    shop  04HBHFCyUVFcf36g9bD6                3.9   
14  hotel  0FfFgX8daJVm3IAntX2P                4.2   

                                              url   longitude status  \
4                           http://churro101.com/  126.924263    ACC   
14  https://www.lottehotel.com/hongdae-l7/ko.html  126.921595    ACC   

                                     primaryImageFile     city prefecture  \
4   spots/images/13302dde-5195-4ca6-90ee-25e85a06e...  Mapo-gu      Seoul   
14  spots/images/ff0224e5-6d3a-4190-a8a4-ddc59103b...  Mapo-gu      Seoul   

          name movieUrl                                         spotImages  \
4   Churro 101           [{'imagePath': 'spots/images/13302dde-5195-4ca...   
14  L7 Hongdae           [{'originUrl': 'https://www.instagram.com/p/CS...   

                          updatedAt  \
4  2023-03-01 15:15:04.544077+00:00   
14 2023-03-01 15:14:52.165099+00:00   

                                       affiliateInfos         phone  \
4                                                       02-336-0331   
14  [{'Category': 'booking', 'URL': 'https://www.b...  02-2289-1000   

    priceLevel                                       openingHours  \
4            0  {'PermanentlyClosed': None, 'WeekdayText': ['月...   
14           0                                                      

   hasInstagramImages   latitude                        createdAt  \
4                True  37.555685 2023-01-11 14:41:03.469000+00:00   
14               True  37.555616 2023-01-12 08:55:40.203000+00:00   

                           instagramImageUrls                googlePlaceId  \
4   [https://www.instagram.com/p/B5okoKYAW-r]  ChIJgf01vMGYfDUR8ZAPgVh0srs   
14  [https://www.instagram.com/p/CSGxoqiJfVc]  ChIJ5WXJar2ZfDUREfMssWUNq2U   

                                       address                  quadKey  \
4   大韓民国 Seoul, Mapo-gu, Eoulmadang-ro, 128 1층  13211032012002031323103   
14        141 Yanghwa-ro, Mapo-gu, Seoul, 大韓民国  13211032012002030323133   

   rakutenHotelMinCharge rakutenHotelNo                               tags  \
4                                        [ひとり, 友達, カップル・パートナー, グルメ, 若者に人気]   
14                                               [ひとり, 家族, 友達, カップル・パートナー]   

   rakutenHotelName rakutenHotelRatingInfo rakutenHotelSpecial  
4                                                               
14

In [178]:
korea_df = pd.concat([exist_tag__df, korea_airport_df], axis=0)
korea_df.head(2)

type                    id  googleReviewScore  \
4    shop  04HBHFCyUVFcf36g9bD6                3.9   
14  hotel  0FfFgX8daJVm3IAntX2P                4.2   

                                              url   longitude status  \
4                           http://churro101.com/  126.924263    ACC   
14  https://www.lottehotel.com/hongdae-l7/ko.html  126.921595    ACC   

                                     primaryImageFile     city prefecture  \
4   spots/images/13302dde-5195-4ca6-90ee-25e85a06e...  Mapo-gu      Seoul   
14  spots/images/ff0224e5-6d3a-4190-a8a4-ddc59103b...  Mapo-gu      Seoul   

          name movieUrl                                         spotImages  \
4   Churro 101           [{'imagePath': 'spots/images/13302dde-5195-4ca...   
14  L7 Hongdae           [{'originUrl': 'https://www.instagram.com/p/CS...   

                          updatedAt  \
4  2023-03-01 15:15:04.544077+00:00   
14 2023-03-01 15:14:52.165099+00:00   

                                       affiliateInfos         phone  \
4                                                       02-336-0331   
14  [{'Category': 'booking', 'URL': 'https://www.b...  02-2289-1000   

    priceLevel                                       openingHours  \
4            0  {'PermanentlyClosed': None, 'WeekdayText': ['月...   
14           0                                                      

   hasInstagramImages   latitude                        createdAt  \
4                True  37.555685 2023-01-11 14:41:03.469000+00:00   
14               True  37.555616 2023-01-12 08:55:40.203000+00:00   

                           instagramImageUrls                googlePlaceId  \
4   [https://www.instagram.com/p/B5okoKYAW-r]  ChIJgf01vMGYfDUR8ZAPgVh0srs   
14  [https://www.instagram.com/p/CSGxoqiJfVc]  ChIJ5WXJar2ZfDUREfMssWUNq2U   

                                       address                  quadKey  \
4   大韓民国 Seoul, Mapo-gu, Eoulmadang-ro, 128 1층  13211032012002031323103   
14        141 Yanghwa-ro, Mapo-gu, Seoul, 大韓民国  13211032012002030323133   

   rakutenHotelMinCharge rakutenHotelNo                               tags  \
4                                        [ひとり, 友達, カップル・パートナー, グルメ, 若者に人気]   
14                                               [ひとり, 家族, 友達, カップル・パートナー]   

   rakutenHotelName rakutenHotelRatingInfo rakutenHotelSpecial  
4                                                               
14


### カテゴリ分類

誰と行く：ひとり,家族,友達,カップル・パートナー
テーマ：グルメ,美容,買い物,観光,推し活・聖地巡り
ホテル：できるだけ安い,立地がいい,映え・コンセプト,日本語が通じる
グルメ：観光客に人気,若者に人気,地元民に人気,芸能人に人気


### プラン型
昼食(restaurant)
観光地・買い物（tourist,shot）
カフェ(cafe)
観光地・買い物（tourist,shot）
夕食(restaurant)
ホテル(hotel)
観光地・買い物（tourist,shot）
昼食(restaurant)
空港(airport)


### TOOD
- spotデータの中のtagをそれぞれ行列にする
- 全パターンの検索クエリ行列を作成する

アウトプットイメージ
[[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0]]


### 最終アウトプットイメージ

（仮）Planスキーマイメージ

{
    planid: str, 
    spots: [
        {
            spotId:str,
            order: int
        }
    ],
    category: str[]
}

In [179]:
# (0,0)は、行列の一行目の中の要素1個目ということ
categories: Dict = {"ひとり": (0,0), "家族": (0,1),"友達": (0,2),"カップル・パートナー": (0,3),"グルメ": (1,0),"美容": (1,1), "買い物": (1,2),"観光": (1,3),"推し活・聖地巡り": (1,4),"できるだけ安い": (2,0), "立地がいい": (2,1),"映え・コンセプト": (2,2),"日本語が通じる": (2,3),"観光客に人気": (3,0),"若者に人気": (3,1),"地元民に人気": (3,2),"芸能人に人気": (3,3)}
categories

{'ひとり': (0, 0),
 '家族': (0, 1),
 '友達': (0, 2),
 'カップル・パートナー': (0, 3),
 'グルメ': (1, 0),
 '美容': (1, 1),
 '買い物': (1, 2),
 '観光': (1, 3),
 '推し活・聖地巡り': (1, 4),
 'できるだけ安い': (2, 0),
 '立地がいい': (2, 1),
 '映え・コンセプト': (2, 2),
 '日本語が通じる': (2, 3),
 '観光客に人気': (3, 0),
 '若者に人気': (3, 1),
 '地元民に人気': (3, 2),
 '芸能人に人気': (3, 3)}

In [180]:
def create_vector(tags: List) -> np.ndarray:
    default_vec: np.ndarray = np.array([[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]])
    for tag in tags:
        val: Tuple = categories.get(tag)
        if(val is not None):
            default_vec[val[0]][val[1]] = 1
    return default_vec

korea_df["tags_vector"] = korea_df["tags"].apply(lambda x: create_vector(x))
with_tag_vector_df = korea_df.loc[:,["id","type","tags_vector","tags"]]
with_tag_vector_df.head(10)


id        type  \
4    04HBHFCyUVFcf36g9bD6        shop   
14   0FfFgX8daJVm3IAntX2P       hotel   
37   18ogSoa0HSEk25qnFJ8H        cafe   
47   1JBduBIm2pXqB4NfcULI        shop   
50   1S273s6gTWCBHWWnFTZX        cafe   
63   1s3dhKze1oMbbZFMJgDL  restaurant   
82   2LLrzKIOTK13lpJ3L6xz       hotel   
92   2XjzwxHUnCTDdigtTdsj        shop   
123  3V0KeEyjRUYzgY4BQwbd  restaurant   
137  3rICd5s9GvavJinsxnel  restaurant   

                                           tags_vector  \
4    [[1, 0, 1, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0...   
14   [[1, 1, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...   
37   [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...   
47   [[0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0...   
50   [[0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0...   
63   [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...   
82   [[1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...   
92   [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...   
123  [[0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0...   
137  [[0, 0, 1, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0...   

                                  tags  
4    [ひとり, 友達, カップル・パートナー, グルメ, 若者に人気]  
14           [ひとり, 家族, 友達, カップル・パートナー]  
37                      [グルメ ,  映えホテル]  
47                               [買い物]  
50                               [買い物]  
63                                  []  
82                           [ひとり, 家族]  
92                      [買い物 ,  若者に人気]  
123                              [グルメ]  
137              [友達, カップル・パートナー, グルメ]

In [181]:
# あらゆる種類の検索条件を作成

import itertools

matrix = [[0,0,0,0,0], [0,0,0,0,0], [0,0,0,0,0], [0,0,0,0,0]]

combinations = list(itertools.product(range(5), repeat=4))

matrices = []
for combo in combinations:
    new_matrix = [row.copy() for row in matrix]
    skip_append = False
    for i, col in enumerate(combo):
        if((i == 0 or i == 2 or i == 3) and col == 4):
            skip_append = True
            continue
        else:
            new_matrix[i][col] = 1
    if(not skip_append):
        matrices.append(new_matrix)


search_condition_list = []
for m in matrices:
    search_condition_list.append(np.array(m))


search_condition_list


[array([[1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]]),
 array([[1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0]]),
 array([[1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0]]),
 array([[1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0]]),
 array([[1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0]]),
 array([[1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0]]),
 array([[1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0]]),
 array([[1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0]]),
 array([[1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0]]),
 array([[1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
       

In [182]:
# 実際に↑で作成した検索クエリとspotの類似度を計算して korea_dfの各行に類似度を入れてみる

def sim(X, Y) -> int:
    multiple = (X - Y)**2
    sum = multiple.sum()
    return sum

def calcurate(tags_vec: np.array, search_condition: np.array) -> int:
    return sim(tags_vec, search_condition)

for index, search_condition in enumerate(search_condition_list):
    korea_df[f"sim_of_search_condition_{index}"] = korea_df["tags_vector"].apply(lambda tags_vec: calcurate(tags_vec, search_condition))

korea_df.head(2)

/var/folders/tm/7v5m6cg144g467bsj7zgsxgc0000gn/T/ipykernel_6970/4228235164.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  korea_df[f"sim_of_search_condition_{index}"] = korea_df["tags_vector"].apply(lambda tags_vec: calcurate(tags_vec, search_condition))
/var/folders/tm/7v5m6cg144g467bsj7zgsxgc0000gn/T/ipykernel_6970/4228235164.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  korea_df[f"sim_of_search_condition_{index}"] = korea_df["tags_vector"].apply(lambda tags_vec: calcurate(tags_vec, search_condition))
/var/folders

type                    id  googleReviewScore  \
4    shop  04HBHFCyUVFcf36g9bD6                3.9   
14  hotel  0FfFgX8daJVm3IAntX2P                4.2   

                                              url   longitude status  \
4                           http://churro101.com/  126.924263    ACC   
14  https://www.lottehotel.com/hongdae-l7/ko.html  126.921595    ACC   

                                     primaryImageFile     city prefecture  \
4   spots/images/13302dde-5195-4ca6-90ee-25e85a06e...  Mapo-gu      Seoul   
14  spots/images/ff0224e5-6d3a-4190-a8a4-ddc59103b...  Mapo-gu      Seoul   

          name movieUrl                                         spotImages  \
4   Churro 101           [{'imagePath': 'spots/images/13302dde-5195-4ca...   
14  L7 Hongdae           [{'originUrl': 'https://www.instagram.com/p/CS...   

                          updatedAt  \
4  2023-03-01 15:15:04.544077+00:00   
14 2023-03-01 15:14:52.165099+00:00   

                                       affiliateInfos         phone  \
4                                                       02-336-0331   
14  [{'Category': 'booking', 'URL': 'https://www.b...  02-2289-1000   

    priceLevel                                       openingHours  \
4            0  {'PermanentlyClosed': None, 'WeekdayText': ['月...   
14           0                                                      

   hasInstagramImages   latitude                        createdAt  \
4                True  37.555685 2023-01-11 14:41:03.469000+00:00   
14               True  37.555616 2023-01-12 08:55:40.203000+00:00   

                           instagramImageUrls                googlePlaceId  \
4   [https://www.instagram.com/p/B5okoKYAW-r]  ChIJgf01vMGYfDUR8ZAPgVh0srs   
14  [https://www.instagram.com/p/CSGxoqiJfVc]  ChIJ5WXJar2ZfDUREfMssWUNq2U   

                                       address                  quadKey  \
4   大韓民国 Seoul, Mapo-gu, Eoulmadang-ro, 128 1층  13211032012002031323103   
14        141 Yanghwa-ro, Mapo-gu, Seoul, 大韓民国  13211032012002030323133   

   rakutenHotelMinCharge rakutenHotelNo                               tags  \
4                                        [ひとり, 友達, カップル・パートナー, グルメ, 若者に人気]   
14                                               [ひとり, 家族, 友達, カップル・パートナー]   

   rakutenHotelName rakutenHotelRatingInfo rakutenHotelSpecial  \
4                                                                
14                                                               

                                          tags_vector  \
4   [[1, 0, 1, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0...   
14  [[1, 1, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0...   

    sim_of_search_condition_0  sim_of_search_condition_1  \
4                           5                          3   
14                          6                          6   

    sim_of_search_condition_2  sim_of_search_condition_3  \
4                           5                          5   
14                          6                          6   

    sim_of_search_condition_4  sim_of_search_condition_5  \
4                           5                          3   
14                          6                          6   

    sim_of_search_condition_6  sim_of_search_condition_7  \
4                           5                          5   
14                          6                          6   

    sim_of_search_condition_8  sim_of_search_condition_9  \
4                           5                          3   
14                          6                          6   

    sim_of_search_condition_10  sim_of_search_condition_11  \
4                            5                           5   
14                           6                           6   

    sim_of_search_condition_12  sim_of_search_condition_13  \
4                            5                           3   
14                           6                           6   

    sim_of_search_condition_14  sim_of_search_condition_15  \
4 

In [200]:
# plan生成する

### プラン型
# 昼食(restaurant)
# 観光地・買い物（tourist,shop）
# カフェ(cafe)
# 観光地・買い物（tourist,shot）
# 夕食(restaurant)
# ホテル(hotel)
# 観光地・買い物（tourist,shot）
# 昼食(restaurant)
# 空港(airport)

import json

plan_spots_list = []

for index in range(320):
    restaurant_list = korea_df[korea_df["type"] == "restaurant"].sort_values(f"sim_of_search_condition_{index}", ascending=True).head(3)["id"].values.tolist()
    tourist_shop_df = korea_df[(korea_df["type"] == "tourist") | (korea_df["type"] == "shop")].sort_values(f"sim_of_search_condition_{index}", ascending=True).head(3)["id"].values.tolist()
    cafe_df = korea_df[korea_df["type"] == "cafe"].sort_values(f"sim_of_search_condition_{index}", ascending=True).head(1)["id"].values.tolist()
    hotel_df = korea_df[korea_df["type"] == "hotel"].sort_values(f"sim_of_search_condition_{index}", ascending=True).head(1)["id"].values.tolist()
    airport_df = korea_df[korea_df["type"] == "airport"].sort_values(f"sim_of_search_condition_{index}", ascending=True).head(1)["id"].values.tolist()

    plan_data = {
        "planId": 1,
        "spots": [
        {
            "spotId": restaurant_list[0],
            "order": 1
        },
        {
            "spotId": tourist_shop_df[0],
            "order": 2
        },
        {
            "spotId": cafe_df[0],
            "order": 3
        },
        {
            "spotId": tourist_shop_df[1],
            "order": 4
        },
        {
            "spotId": restaurant_list[1],
            "order": 5
        },
        {
            "spotId": hotel_df[0],
            "order": 6
        },
        {
            "spotId": tourist_shop_df[2],
            "order": 7
        },
        {
            "spotId": restaurant_list[2],
            "order": 8
        },
        {
            "spotId": airport_df[0],
            "order": 9
        },
        ]
    }

    plan_spots_list.append(json.dumps(plan_data))


plan_spots_list




['{"planId": 1, "spots": [{"spotId": "3V0KeEyjRUYzgY4BQwbd", "order": 1}, {"spotId": "WJ5nYWCGDKbrr6fBY8VT", "order": 2}, {"spotId": "SDKwevgDEznZnI98IzTo", "order": 3}, {"spotId": "u3Ga6HsfvlKgRaXn3Qo6", "order": 4}, {"spotId": "pcSKXch5oFMU6MB4zdbC", "order": 5}, {"spotId": "C3nGjzrkzKv9HJuMGT2X", "order": 6}, {"spotId": "SvflngJiEhdCr8pd7JMz", "order": 7}, {"spotId": "O1PpUSvoj8ie9JPZM1bj", "order": 8}, {"spotId": "mR58qvOdnBcICh2e8xz5", "order": 9}]}',
 '{"planId": 1, "spots": [{"spotId": "3V0KeEyjRUYzgY4BQwbd", "order": 1}, {"spotId": "04HBHFCyUVFcf36g9bD6", "order": 2}, {"spotId": "SDKwevgDEznZnI98IzTo", "order": 3}, {"spotId": "u3Ga6HsfvlKgRaXn3Qo6", "order": 4}, {"spotId": "pcSKXch5oFMU6MB4zdbC", "order": 5}, {"spotId": "C3nGjzrkzKv9HJuMGT2X", "order": 6}, {"spotId": "TOvDn1AP19kdJsj8ZKs4", "order": 7}, {"spotId": "O1PpUSvoj8ie9JPZM1bj", "order": 8}, {"spotId": "mR58qvOdnBcICh2e8xz5", "order": 9}]}',
 '{"planId": 1, "spots": [{"spotId": "3V0KeEyjRUYzgY4BQwbd", "order": 1}, {"sp

In [ ]:
dareto = ["ひとり", "家族","友達","カップル・パートナー"]
terma  = ["グルメ","美容","買い物","観光","推し活・聖地巡り"]
hotel = ["できるだけ安い","立地がいい","映え・コンセプト","日本語が通じる"]
gurume = ["観光客に人気","若者に人気","地元民に人気","芸能人に人気"]


dareto_vec = [[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0]]
terma_vec = [[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1]]
hotel_vec = [[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0]]
gurume_vec = [[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0]]

# TODO: 各パターンの行列を作成する

In [61]:
test = list()
test.append(np.array([[0,1,0,0],[0,0,1,0],[1,0,0,1]]))
test.append(np.array([[0,1,0,0],[0,0,1,0],[1,0,0,0]]))
test

[array([[0, 1, 0, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 1]]),
 array([[0, 1, 0, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 0]])]

行列間の差の2乗を計算
一致しているほど計算結果が小さくなる（最小0）

spot1:
    誰と：家族
    テーマ：買い物
    ホテル：できるだけ安い・日本語通じる

=> [[0,1,0,0],[0,0,1,0],[1,0,0,1]]

spot2:
    誰と：ひとり・家族・友達・カップルパートナー
    テーマ：グルメ・美容・買い物
    ホテル：できるだけ安い・中心地にある・日本語通じる

=> [[1,1,1,1],[1,1,1,0],[1,1,0,1]]

search_condition:
    誰と：カップルパートナー
    テーマ：買い物
    ホテル：日本語通じる

=> [[0,0,0,1],[0,0,1,0],[0,0,0,1]]


In [57]:
import numpy as np


In [63]:
spot1 = np.array([[0,1,0,0],[0,0,1,0],[1,0,0,1]])
spot1

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 1]])

In [59]:
search_condition = np.array([[0,0,0,1],[0,0,1,0,0],[0,0,0,1]])
search_condition

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [60]:
spot2 = np.array([[1,1,1,1],[1,1,1,0],[1,1,0,1]])
spot2

array([[1, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 0, 1]])

In [61]:
def sim(X, Y):
    multiple = (X - Y)**2
    sum = multiple.sum()
    return sum


result1 = sim(spot1, search_condition)
result2 = sim(spot2, search_condition)
print(f"spot1と検索条件の類似度：{result1}")
print(f"spot2と検索条件の類似度：{result2}")

print("spot1の方が検索条件に近い")


spot1と検索条件の類似度：3
spot2と検索条件の類似度：7
spot1の方が検索条件に近い
