行列間の差の2乗を計算
一致しているほど計算結果が小さくなる（最小0）

spot1:
    誰と：家族
    テーマ：買い物
    ホテル：できるだけ安い・日本語通じる

=> [[0,1,0,0],[0,0,1,0],[1,0,0,1]]

spot2:
    誰と：ひとり・家族・友達・カップルパートナー
    テーマ：グルメ・美容・買い物
    ホテル：できるだけ安い・中心地にある・日本語通じる

=> [[1,1,1,1],[1,1,1,0],[1,1,0,1]]

search_condition:
    誰と：カップルパートナー
    テーマ：買い物
    ホテル：日本語通じる

=> [[0,0,0,1],[0,0,1,0],[0,0,0,1]]


In [57]:
import numpy as np


In [58]:
spot1 = np.array([[0,1,0,0],[0,0,1,0],[1,0,0,1]])
spot1

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 1]])

In [59]:
search_condition = np.array([[0,0,0,1],[0,0,1,0],[0,0,0,1]])
search_condition

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [60]:
spot2 = np.array([[1,1,1,1],[1,1,1,0],[1,1,0,1]])
spot2

array([[1, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 0, 1]])

In [61]:
def sim(X, Y):
    multiple = (X - Y)**2
    sum = multiple.sum()
    return sum


result1 = sim(spot1, search_condition)
result2 = sim(spot2, search_condition)
print(f"spot1と検索条件の類似度：{result1}")
print(f"spot2と検索条件の類似度：{result2}")

print("spot1の方が検索条件に近い")


spot1と検索条件の類似度：3
spot2と検索条件の類似度：7
spot1の方が検索条件に近い
