In [85]:
import firebase_admin
from firebase_admin import credentials,firestore,initialize_app
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 100)
from typing import List,Dict,Tuple


In [87]:
default_vec = np.array([[0,0,0,0],[0,0,0,0]])
default_vec[0][0] = 1
type(default_vec)

numpy.ndarray

In [35]:
cred = credentials.Certificate("/Users/kinsho/workspace/micce-firebase-secret-key/micce-travel-firebase-adminsdk-3fcnp-b289dc5911.json")
app = initialize_app(cred, name="micce-app")


ValueError: Firebase app named "micce-app" already exists. This means you called initialize_app() more than once with the same app name as the second argument. Make sure you provide a unique name every time you call initialize_app().

In [39]:
firestore_client  = firestore.client(app=app)
spots = firestore_client.collection("Spot").stream()


In [40]:
spot_list = list()
for spot in spots:
    spot_list.append(spot.to_dict())

df = pd.DataFrame(spot_list)

df

type                    id   longitude  \
0     restaurant  01WKW1kqcDIry4xb3kNY  134.649435   
1     restaurant  02FsRcZNGrHoXsSuJFXk  128.766697   
2        tourist  02raxFhXNoRmzXXPk0Zo  129.124401   
3          hotel  039zAGnA0gIyIQ0Hn5Pz  139.702054   
4           shop  04HBHFCyUVFcf36g9bD6  126.924263   
...          ...                   ...         ...   
2103  restaurant  zmCMjbq9ymdhCjWSlMGH  135.515714   
2104     tourist  znHCfy3HszJnZSFIE44Q  135.775240   
2105  restaurant  zqKx1kwYPVermTKJ4LzE  140.310287   
2106       other  zroKz8m43M0FrE4kTFL9  139.765665   
2107  restaurant  zt9dZ45VIMq2IAayHt77  135.501085   

                                                    url  googleReviewScore  \
0                                                                      4.0   
1                                                                      0.0   
2     https://korean.visitkorea.or.kr/detail/ms_deta...                4.2   
3                          http://gracery.com/shinjuku/                4.3   
4                                 http://churro101.com/                3.9   
...                                                 ...                ...   
2103                    https://batongroup.shop-pro.jp/                4.1   
2104                                                                   0.0   
2105                        http://www.spice-magic.com/                4.1   
2106                                                                   0.0   
2107                                                                   4.0   

     prefecture movieUrl     city  \
0           兵庫県     None      姫路市   
1          None     None      キメ市   
2         Busan     None   Nam-gu   
3           東京都     None      新宿区   
4         Seoul     None  Mapo-gu   
...         ...      ...      ...   
2103        大阪府     None      大阪市   
2104        京都府     None      京都市   
2105        山形県     None      山形市   
2106        東京都     None      八丈島   
2107        大阪府     None      大阪市   

                                       primaryImageFile  \
0     spots/images/26555cc0-eec1-4621-a10f-583b96cae...   
1                                                  None   
2     spots/images/60a692d3-5c92-4dbb-9d22-c2ed31f34...   
3     spots/images/7c0c50fa-23e6-4b0e-a09c-ef0b5a56c...   
4     spots/images/13302dde-5195-4ca6-90ee-25e85a06e...   
...                                                 ...   
2103  spots/images/544152af-0483-4fe1-83a9-d5c3c4c2b...   
2104                                               None   
2105  spots/images/7d72bfe4-a7a2-438d-9073-d24d04b5f...   
2106                                               None   
2107  spots/images/afc155fc-4f51-4e9b-94cd-4cdccd0c5...   

                              name  ...                        createdAt  \
0                            トンデムン  ... 2023-02-16 08:10:25.728000+00:00   
1                            석쇠불고기  ... 2023-02-23 09:12:10.126000+00:00   
2                       五六島スカイウォーク  ... 2023-03-01 07:09:10.348000+00:00   
3                      ホテルグレイスリー新宿  ... 2023-01-22 10:22:48.569000+00:00   
4                       Churro 101  ... 2023-01-11 14:41:03.469000+00:00   
...                            ...  ...                              ...   
2103                       コバトパン工場  ... 2023-02-03 02:08:55.145000+00:00   
2104                        花見小路通り  ... 2022-12-27 07:48:45.189000+00:00   
2105  スパイスマジック インディアン レストラン 西バイパス店  ... 2022-12-28 15:06:38.811000+00:00   
2106                    大賀郷７６４０−１４  ... 2023-02-08 11:16:48.922000+00:00   
2107                     すき焼･鍋 なべや  ... 2022-12-28 17:30:50.029000+00:00   

                    googlePlaceId                                     address  \
0     ChIJp65uLzzhVDURN85t-6Ojijk    日本、〒672-8083 兵庫県姫路市飾磨区城南町３丁目５３ 韓国家庭料理東大門   
1     ChIJVUgnRsbJaDURElhJTYA6fHE                                    大韓民国 キメ市   
2     ChIJVRLdCsjtaDURcdummQTLnRk         137 Oryuk-doro, Nam-gu, Busan, 大韓民国   
3     ChIJF-U1JdiMGGARaay7KIrrtZ0  

In [58]:
df = df.fillna("")
exist_tags_df = df[df["tags"] != ""]
exist_tags_df.head(5)

type                    id   longitude  \
4    shop  04HBHFCyUVFcf36g9bD6  126.924263   
13  hotel  0FfFgX8daJVm3IAntX2P  126.921595   
34   cafe  18ogSoa0HSEk25qnFJ8H  126.922055   
43   shop  1JBduBIm2pXqB4NfcULI  126.922194   
46   cafe  1S273s6gTWCBHWWnFTZX  127.024908   

                                              url  googleReviewScore  \
4                           http://churro101.com/                3.9   
13  https://www.lottehotel.com/hongdae-l7/ko.html                4.2   
34      https://www.instagram.com/dingacakehouse/                4.0   
43                                                               3.9   
46                                                               4.1   

   prefecture movieUrl        city  \
4       Seoul              Mapo-gu   
13      Seoul              Mapo-gu   
34      Seoul              Mapo-gu   
43      Seoul              Mapo-gu   
46      Seoul           Gangnam-gu   

                                     primaryImageFile              name  \
4   spots/images/13302dde-5195-4ca6-90ee-25e85a06e...        Churro 101   
13  spots/images/ff0224e5-6d3a-4190-a8a4-ddc59103b...        L7 Hongdae   
34  spots/images/908f8c3d-27a0-42ae-84da-bd29568cd...  Dinga Cake House   
43  spots/images/f1c552cf-39b1-422c-8e9a-6b55da5fa...           나이키 홍대점   
46  spots/images/5040ca36-a7d2-4c1d-be2b-d5ba81eda...      Saddler Haus   

                                           spotImages status  \
4   [{'originUrl': 'https://www.instagram.com/p/B5...    ACC   
13  [{'originUrl': 'https://www.instagram.com/p/CS...    ACC   
34  [{'originUrl': 'https://www.instagram.com/p/CC...    ACC   
43  [{'originUrl': 'https://www.instagram.com/p/Cg...    ACC   
46  [{'imagePath': 'spots/images/5040ca36-a7d2-4c1...    ACC   

                          updatedAt  priceLevel          phone  \
4  2023-03-01 15:15:04.544077+00:00           0    02-336-0331   
13 2023-03-01 15:14:52.165099+00:00           0   02-2289-1000   
34 2023-03-01 15:15:11.267230+00:00           0                  
43 2023-03-01 15:15:09.833518+00:00           0    02-334-6593   
46 2023-03-01 15:15:13.219871+00:00           0  070-8265-5541   

                                       affiliateInfos  \
4                                                       
13  [{'Category': 'booking', 'URL': 'https://www.b...   
34                                                      
43                                                      
46                                                      

                                         openingHours  hasInstagramImages  \
4   {'PermanentlyClosed': None, 'WeekdayText': ['月...                True   
13                                                                   True   
34  {'PermanentlyClosed': None, 'WeekdayText': ['月...                True   
43  {'PermanentlyClosed': None, 'WeekdayText': ['月...                True   
46  {'PermanentlyClosed': None, 'WeekdayText': ['月...                True   

     latitude                                 instagramImageUrls  \
4   37.555685          [https://www.instagram.com/p/B5okoKYAW-r]   
13  37.555616          [https://www.instagram.com/p/CSGxoqiJfVc]   
34  37.563361          [https://www.instagram.com/p/CCvjqEuhku-]   
43  37.554240          [https://www.instagram.com/p/CgI02AZvleT]   
46  37.519342  [https://www.instagram.com/p/CabkZ7klYZR, http...   

                          createdAt                googlePlaceId  \
4  2023-01-11 14:41:03.469000+00:00  ChIJgf01vMGYfDUR8ZAPgVh0srs   
13 2023-01-12 08:55:40.203000+00:00  ChIJ5WXJar2ZfDUREfMssWUNq2U   
34 2023-01-11 14:41:11.279000+00:00  ChIJJeopst-ZfDUR2DLwYJ8sfLI   
43 2023-02-02 12:55:13.281000+00:00  ChIJ49vWwx6ZfDURvKE5v4_g-2k   
46 2022-12-26 15:06:47.087000+00:00  ChIJWbV4PxijfDURPuxW5EXM2uU   

                                              address  \
4          大韓民国 Seoul, Mapo-gu, Eoulmadang-ro, 128 1층   
13               141 Yanghwa-ro, Mapo-gu, Seoul, 大韓民国   
34         68 Donggyo-ro 29-gil,


### カテゴリ分類

誰と行く：ひとり,家族,友達,カップル・パートナー
テーマ：グルメ,美容,買い物,観光,推し活・聖地巡り
ホテル：できるだけ安い,立地がいい,映え・コンセプト,日本語が通じる
グルメ：観光客に人気,若者に人気,地元民に人気,芸能人に人気


### プラン型
昼食
観光地・買い物
カフェ
観光地・買い物
夕食
ホテル
観光地・買い物
昼食
空港


### TOOD
- spotデータの中のtagをそれぞれ行列にする
- 全パターンの検索クエリ行列を作成する

アウトプットイメージ
[[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0],[1,0,0,0,0]]

In [82]:
# (0,0)は、行列の一行目の中の要素1個目ということ
categories: Dict = {"ひとり": (0,0), "家族": (0,1),"友達": (0,2),"カップル・パートナー": (0,3),"グルメ": (1,0),"美容": (1,1), "買い物": (1,2),"観光": (1,3),"推し活・聖地巡り": (1,4),"できるだけ安い": (2,0), "立地がいい": (2,1),"映え・コンセプト": (2,2),"日本語が通じる": (2,3),"観光客に人気": (3,0),"若者に人気": (3,1),"地元民に人気": (3,2),"芸能人に人気": (3,3)}
categories

{'ひとり': (0, 0),
 '家族': (0, 1),
 '友達': (0, 2),
 'カップル・パートナー': (0, 3),
 'グルメ': (1, 0),
 '美容': (1, 1),
 '買い物': (1, 2),
 '観光': (1, 3),
 '推し活・聖地巡り': (1, 4),
 'できるだけ安い': (2, 0),
 '立地がいい': (2, 1),
 '映え・コンセプト': (2, 2),
 '日本語が通じる': (2, 3),
 '観光客に人気': (3, 0),
 '若者に人気': (3, 1),
 '地元民に人気': (3, 2),
 '芸能人に人気': (3, 3)}

In [96]:
def create_vector(tags: List) -> np.ndarray:
    default_vec: np.ndarray = np.array([[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]])
    for tag in tags:
        val: Tuple = categories.get(tag)
        if(val is not None):
            default_vec[val[0]][val[1]] = 1
    return default_vec

exist_tags_df["tags_vector"] = exist_tags_df["tags"].apply(lambda x: create_vector(x))
with_tag_vector_df = exist_tags_df.loc[:,["id","type","tags_vector","tags"]]
with_tag_vector_df

# TODO：続き
# ある一個の検索クエリを作成してランキング作ってみる

id        type  \
4     04HBHFCyUVFcf36g9bD6        shop   
13    0FfFgX8daJVm3IAntX2P       hotel   
34    18ogSoa0HSEk25qnFJ8H        cafe   
43    1JBduBIm2pXqB4NfcULI        shop   
46    1S273s6gTWCBHWWnFTZX        cafe   
58    1s3dhKze1oMbbZFMJgDL  restaurant   
77    2LLrzKIOTK13lpJ3L6xz       hotel   
86    2XjzwxHUnCTDdigtTdsj        shop   
113   3V0KeEyjRUYzgY4BQwbd  restaurant   
126   3rICd5s9GvavJinsxnel  restaurant   
129   3vG18qboP2zuoJRzpxCM  restaurant   
147   4OBSNlhsswqEjiMwf06G  restaurant   
179   5PF9QMGF5rbqzCZMgwgt        shop   
190   5kIlDoZqAj1E8Sb8O3PN        cafe   
255   8CmctiCBx0aDXb5qF628       other   
267   8UBVGjU9QgcaWsCpvS6f     tourist   
282   8sIFtKZnj05BmsRLhJoc     tourist   
294   9XXLX0yGEcj9aCGhqM6v     tourist   
324   AEmd0rPFtSKniqMPgVxy     tourist   
413   C3nGjzrkzKv9HJuMGT2X       hotel   
537   FZ4tkopQGSfWqhbiHXpg        cafe   
548   FlynUue2XpMVMnnBm4Nl     tourist   
562   GKprDRlF1l8zUoWg1x2g  restaurant   
651   IviWlkv3DCYpBTknmwlS  restaurant   
655   J6fF4Pem4VTerELeD5ZG        shop   
663   JQIaggyQ4GtaViK3ZAID        cafe   
668   JerhoJ9HdCBai8g7D2Hs       hotel   
673   JvRxiqh69vERvIAqiM9g        shop   
724   LCjQYjI25FV4FOUYPzM0  restaurant   
741   Lb0ZXVHHz8FRO9bzDcTv     tourist   
745   LkmUzDONUtyCwUBxoy9e        cafe   
794   N2rFeGWeHFRCcKdQ7W1N        shop   
826   O1PpUSvoj8ie9JPZM1bj  restaurant   
832   OBKRFSWYy8AszFli2uM9        shop   
845   OVFoLiC1NhxFn31rjpyk       hotel   
862   P2DZhL0BGwMucQgrAPRi  restaurant   
874   PJ2hXaYuHpmxEC21IAO0        cafe   
884   PbOWcVBRCP3VTYA1idYg        shop   
932   Qoal2EXWgMskrBptQ9PC       hotel   
948   RF2IDck9YDcLDzHQC2lX        cafe   
986   SDKwevgDEznZnI98IzTo        cafe   
993   SOZpjjGSAaMcToRleR0e        shop   
1008  SjKVLOiInwtIxbOkjvOf       hotel   
1010  SmegkADWWl3C0UCpfBQ7       hotel   
1018  SvflngJiEhdCr8pd7JMz     tourist   
1036  TOvDn1AP19kdJsj8ZKs4        shop   
1065  USsS2L6EaBWDStW7ON7S        shop   
1089  V42Ndtl7KtrxedSGlg4T  restaurant   
1120  WJ5nYWCGDKbrr6fBY8VT     tourist   
1129  WnUmS7C8agaZvdoe8r8F     tourist   
1132  X0czZDtw2FKqtxkHQAbc       hotel   
1153  XQd3lR0NXKndgkG1ti4q       hotel   
1166  XiZIjQ0fQ029yjzBatOm     tourist   
1180  YC396ptawW3UDnsZOwjT  restaurant   
1195  YUktMtz1FlVqdaGhQmRV        cafe   
1227  ZIviRIEAQ48BsC1B1hKU        cafe   
1228  ZNii7kYsY9MK0StPtW8D     tourist   
1239  ZnVdOpoCtsjV95PEjVBP     tourist   
1251  aCQY6Si2ESTJvOF6OVQW       hotel   
1273  avBhZSwDClfrr5zoeWeB        shop   
1274  avGNaGP9eJDbXhz2IZiw  restaurant   
1372  dtQgNUyzVTOTkZZbgD97  restaurant   
1379  e5qpagdDJKSh8oarRV7v        shop   
1413  f5BshhWTZJrcLdEVKB6O        shop   
1417  fAdacTAG1LungyvnevyM        shop   
1428  fZyZRf7nlQXYG4k6tEfe       hotel   
1432  fm0AE8VAT560iwWE419l     tourist   
1467  gg5XhzOhwzjOhZ81rSmT     tourist   
1529  icjHDiVKZSpcVC7HbCNM        shop   
1531  ii4GefdpcQbcdearLsuM     tourist   
1536  ioakZBPsYAoMXYIWoLni     tourist   
1541  j46R7l401FcESfEjMZM7        shop   
1566  jwKJW4dWn3F4BRm3SVye       hotel   
1571  k1YlUYWCqo9XDIqMxHVj        shop   
1588  kQvEOnEjXuyDdmv3zD4E        shop   
1595  keS6AxXSL11mvc4HQck1     tourist   
1596  khEULExwlM3dCtMmpz2k     tourist   
1656  mlDm8ypncfOxAdGzKvm4        shop   
1668  n9kh4lU8tT40yCWXTndO        shop   
1683  nZbp6i8mNeul7xPW3GtU        shop   
1716  ofVp6FGWCCLEgJLilmfj  restaurant   
1726  oyFzHoyvalr1T3GitnpQ  restaurant   
1744  pcSKXch5oFMU6MB4zdbC  restaurant   
1815  rTBmSF4fhA7VuI8eFkjd  restaurant   
1870  t5emOrZHw1jgpOiEkl6i     tourist   
1888  tSy9lXQc1GvLhgl6bXBG  restaurant   
1893  tgHcxLbLQa3nBIJEDY4G       hotel   
1905  ttBn4Mp7JhvmVebKIAEi        shop   
1909  u2N8K3WZnZuOaLwei6jS     tourist   
1911  u3Ga6HsfvlKgRaXn3Qo6     tourist   
1922  uPV84yZ0s7frsf4bwaDh        cafe   
1938  uvxdB4HRrtNyrlbzcohU        shop   
1995  wzCH2UqJNHw4wLgxoaBU     tourist   
2040  yEiF8NwZNL4nIEr4ZXxq     tourist   
2060  ycnOX2A0zwcsmuVlOLLW        

In [ ]:
dareto = ["ひとり", "家族","友達","カップル・パートナー"]
terma  = ["グルメ","美容","買い物","観光","推し活・聖地巡り"]
hotel = ["できるだけ安い","立地がいい","映え・コンセプト","日本語が通じる"]
gurume = ["観光客に人気","若者に人気","地元民に人気","芸能人に人気"]


dareto_vec = [[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0]]
terma_vec = [[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1]]
hotel_vec = [[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0]]
gurume_vec = [[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0]]

# TODO: 各パターンの行列を作成する

In [61]:
test = list()
test.append(np.array([[0,1,0,0],[0,0,1,0],[1,0,0,1]]))
test.append(np.array([[0,1,0,0],[0,0,1,0],[1,0,0,0]]))
test

[array([[0, 1, 0, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 1]]),
 array([[0, 1, 0, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 0]])]

行列間の差の2乗を計算
一致しているほど計算結果が小さくなる（最小0）

spot1:
    誰と：家族
    テーマ：買い物
    ホテル：できるだけ安い・日本語通じる

=> [[0,1,0,0],[0,0,1,0],[1,0,0,1]]

spot2:
    誰と：ひとり・家族・友達・カップルパートナー
    テーマ：グルメ・美容・買い物
    ホテル：できるだけ安い・中心地にある・日本語通じる

=> [[1,1,1,1],[1,1,1,0],[1,1,0,1]]

search_condition:
    誰と：カップルパートナー
    テーマ：買い物
    ホテル：日本語通じる

=> [[0,0,0,1],[0,0,1,0],[0,0,0,1]]


In [57]:
import numpy as np


In [63]:
spot1 = np.array([[0,1,0,0],[0,0,1,0],[1,0,0,1]])
spot1

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 1]])

In [59]:
search_condition = np.array([[0,0,0,1],[0,0,1,0,0],[0,0,0,1]])
search_condition

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [60]:
spot2 = np.array([[1,1,1,1],[1,1,1,0],[1,1,0,1]])
spot2

array([[1, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 0, 1]])

In [61]:
def sim(X, Y):
    multiple = (X - Y)**2
    sum = multiple.sum()
    return sum


result1 = sim(spot1, search_condition)
result2 = sim(spot2, search_condition)
print(f"spot1と検索条件の類似度：{result1}")
print(f"spot2と検索条件の類似度：{result2}")

print("spot1の方が検索条件に近い")


spot1と検索条件の類似度：3
spot2と検索条件の類似度：7
spot1の方が検索条件に近い
